$version: "2"
namespace com.weekly.budgeter.common

@documentation("Represents the ID of a budget.")
string BudgetId

@documentation("The name associated witha a budget")
@length(min: 1, max: 20)
string BudgetName

@documentation("The weekly budget limit. How much is allocated for spending in a given week.")
integer WeeklyLimit

@documentation("An email identifying accounts with access to this budget")
@pattern("^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$") // This regex was generated by ChatGPT
string Email

@documentation("Identifies a user with access to the budget.")
union AllowedUser {
    email: Email,
}

@documentation("A list of emails with access to this budget")
@length(min: 1, max: 10)
list AllowedUsers {
    member: AllowedUser,
}

structure Budget {
    @required
    budgetId: BudgetId,

    @required
    name: BudgetName,

    @required
    limit: WeeklyLimit,

    @required
    allowedUsers: AllowedUsers,
}

list Budgets {
    member: Budget,
}
